export const LOGOUT = 'USER_LOGOUT';

export enum Login {
  REQUEST = 'LOGIN_REQUEST',
  SUCCESS = 'LOGIN_SUCCESS',
  FAILURE = 'LOGIN_FAILURE',
}

export enum Logout {
  REQUEST = 'LOGOUT_REQUEST',
  SUCCESS = 'LOGOUT_SUCCESS',
  FAILURE = 'LOGOUT_FAILURE',
}
