export const LOGOUT = 'USER_LOGOUT';

export enum Login {
  REQUEST = 'LOGIN_REQUEST',
  SUCCESS = 'LOGIN_SUCCESS',
  FAILURE = 'LOGIN_FAILURE',
}

export enum Logout {
  REQUEST = 'LOGOUT_REQUEST',
  SUCCESS = 'LOGOUT_SUCCESS',
  FAILURE = 'LOGOUT_FAILURE',
}

export enum CompaniesFetch {
  REQUEST = 'COMPANIES_FETCH_REQUEST',
  SUCCESS = 'COMPANIES_FETCH_SUCCESS',
  FAILURE = 'COMPANIES_FETCH_FAILURE',
}

export enum AddCompany {
  REQUEST = 'COMPANY_ADD_REQUEST',
  SUCCESS = 'COMPANY_ADD_SUCCESS',
  FAILURE = 'COMPANY_ADD_FAILURE',
}

export enum RemoveCompany {
  REQUEST = 'COMPANY_REMOVE_REQUEST',
  SUCCESS = 'COMPANY_REMOVE_SUCCESS',
  FAILURE = 'COMPANY_REMOVE_FAILURE',
}

export enum SubDivisionsFetch {
  REQUEST = 'SUBDIVISIONS_FETCH_REQUEST',
  SUCCESS = 'SUBDIVISIONS_FETCH_SUCCESS',
  FAILURE = 'SUBDIVISIONS_FETCH_FAILURE',
}

export enum AddSubDivision {
  REQUEST = 'SUBDIVISION_ADD_REQUEST',
  SUCCESS = 'SUBDIVISION_ADD_SUCCESS',
  FAILURE = 'SUBDIVISION_ADD_FAILURE',
}

export enum RemoveSubDivision {
  REQUEST = 'SUBDIVISION_REMOVE_REQUEST',
  SUCCESS = 'SUBDIVISION_REMOVE_SUCCESS',
  FAILURE = 'SUBDIVISION_REMOVE_FAILURE',
}
